// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering_Numbers.Data;

#nullable disable

namespace OrderingNumbers.Migrations
{
    [DbContext(typeof(OrderingNumbersDbContext))]
    partial class OrderingNumbersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ordering_Numbers.Models.Number", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NumbersListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumbersListId");

                    b.ToTable("Numbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7980f2dc-999c-482d-aea1-11c247c84cca"),
                            Value = 0
                        });
                });

            modelBuilder.Entity("Ordering_Numbers.Models.NumbersList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrderingTimeMilliseconds")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NumbersLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8818db8a-4214-416f-a679-62b640fec184"),
                            OrderType = "Unsorted",
                            OrderingTimeMilliseconds = 0L
                        });
                });

            modelBuilder.Entity("Ordering_Numbers.Models.Number", b =>
                {
                    b.HasOne("Ordering_Numbers.Models.NumbersList", null)
                        .WithMany("Numbers")
                        .HasForeignKey("NumbersListId");
                });

            modelBuilder.Entity("Ordering_Numbers.Models.NumbersList", b =>
                {
                    b.Navigation("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
